# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [1]:
import numpy as np


2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [5]:
cupcakes=np.array(["Flour=2","Sugar=0.75","Eggs=2","Milk=1","Butter=0.5"])
cupcakes

array(['Flour=2', 'Sugar=0.75', 'Eggs=2', 'Milk=1', 'Butter=0.5'],
      dtype='<U10')

3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [9]:
recipes=np.genfromtxt('recipes.csv', delimiter=',')
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [15]:
print(recipes)
Cupcakes=recipes[0:1,0:]
print("Cupcakes=",Cupcakes)
Pancake =recipes[1:2,0:]
print("Pancake =",Pancake )
Cookie =recipes[2:3,0:]
print("Cookie =",Cookie)
Bread =recipes[3:4,0:]
print("Bread =",Bread)




[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]
Cupcakes= [[2.   0.75 2.   1.   0.5 ]]
Pancake = [[1.    0.125 1.    1.    0.125]]
Cookie = [[2.75 1.5  1.   0.   1.  ]]
Bread = [[4.  0.5 2.  2.  0.5]]


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [18]:
eggs=recipes[0:,2:3]
eggs


array([[2.],
       [1.],
       [1.],
       [2.]])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [19]:
eggs==1

array([[False],
       [ True],
       [ True],
       [False]])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [32]:
cookies =recipes[2:3,0:]
print("Cookie =",cookies)

Cookie = [[2.75 1.5  1.   0.   1.  ]]


8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [21]:
double_batch=Cupcakes*Cupcakes
double_batch

array([[4.    , 0.5625, 4.    , 1.    , 0.25  ]])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [33]:
grocery_list=np.concatenate((cookies, double_batch))
grocery_list


array([[2.75  , 1.5   , 1.    , 0.    , 1.    ],
       [4.    , 0.5625, 4.    , 1.    , 0.25  ]])